In [14]:
import numpy as np
# Arrays
prices=np.array([5000,10000,15000,20000])
new_prices = prices * 1.10
print(new_prices)

[ 5500. 11000. 16500. 22000.]

In [11]:
# Vectorization
prices = np.array([500, 1000, 1500, 2000, 2500])
quantity = np.array([2, 3, 4, 2, 5])

total_sales = prices * quantity

print("Total Sales:", total_sales)

total_revenue = np.sum(total_sales)

print("Total Revenue:", total_revenue)

Total Sales: [ 1000  3000  6000  4000 12500]
Total Revenue: 26500

In [10]:
# Arrays operations

sales = np.array([10000, 20000, 30000, 40000, 50000])
print("Total:", np.sum(sales))
print("Average:", np.mean(sales))
print("Maximum:", np.max(sales))
print("Minimum:", np.min(sales))

increased_sales = sales * 1.10
print("Increased Sales:", increased_sales)

Total: 150000
Average: 30000.0
Maximum: 50000
Minimum: 10000
Increased Sales: [11000. 22000. 33000. 44000. 55000.]

In [12]:
# Indexing

sales = np.array([10000, 20000, 30000, 40000, 50000])
print(sales[0])
print(sales[-1])
print(sales[2])
print(sales[1:4])

10000
50000
30000
[20000 30000 40000]

In [13]:
# Pandas Series
import pandas as pd
prices = pd.Series(
    [500, 1000, 1500, 2000, 2500],
    name="Price"
)
print(prices)

print("Total:", prices.sum())
print("Average:", prices.mean())
print("Maximum:", prices.max())
print("Minimum:", prices.min())

0     500
1    1000
2    1500
3    2000
4    2500
Name: Price, dtype: int64
Total: 7500
Average: 1500.0
Maximum: 2500
Minimum: 500

In [ ]:
# Pandas DataFrame

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Electronics"],
    "Price": [85000, 1500, 3000, 25000, 18000],
    "Quantity": [2, 5, 3, 2, 1]
}

df = pd.DataFrame(data)

df

In [15]:
# creating CSV File
import pandas as pd

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Electronics"],
    "Price": [85000, 1500, 3000, 25000, 18000],
    "Quantity": [2, 5, 3, 2, 1]
}

df = pd.DataFrame(data)

df.to_csv("products.csv", index=False)
df = pd.read_csv("products.csv")

df
pd.read_csv("products.csv")

    Product     Category  Price  Quantity
0    Laptop  Electronics  85000         2
1     Mouse  Accessories   1500         5
2  Keyboard  Accessories   3000         3
3   Monitor  Electronics  25000         2
4   Printer  Electronics  18000         1

In [16]:
# Reading the excel files
df.to_excel("products.xlsx", index=False)
df_excel = pd.read_excel("products.xlsx")

df_excel
print(df_excel.shape)

(5, 4)

In [17]:

# Reading JSON Files

df.to_json("products.json", orient="records")

df_json = pd.read_json("products.json")

df_json

    Product     Category  Price  Quantity
0    Laptop  Electronics  85000         2
1     Mouse  Accessories   1500         5
2  Keyboard  Accessories   3000         3
3   Monitor  Electronics  25000         2
4   Printer  Electronics  18000         1

In [18]:
#  Slecting columns
df[["Product", "Category", "Price"]]
df[df["Price"] > 10000]

   Product     Category  Price  Quantity
0   Laptop  Electronics  85000         2
3  Monitor  Electronics  25000         2
4  Printer  Electronics  18000         1

In [19]:
# Filtering
df[df["Category"] == "Electronics"]

   Product     Category  Price  Quantity
0   Laptop  Electronics  85000         2
3  Monitor  Electronics  25000         2
4  Printer  Electronics  18000         1

In [20]:
# Sorting Data
df.sort_values("Quantity")

    Product     Category  Price  Quantity
4   Printer  Electronics  18000         1
0    Laptop  Electronics  85000         2
3   Monitor  Electronics  25000         2
2  Keyboard  Accessories   3000         3
1     Mouse  Accessories   1500         5

In [21]:
# GroupBy
df.groupby("Category")["Quantity"].sum()

Category
Accessories    8
Electronics    5
Name: Quantity, dtype: int64

In [22]:
# Aggregation
df.groupby("Category")["Price"].agg(["sum", "mean", "min", "max"])

                sum          mean    min    max
Category
Accessories    4500   2250.000000   1500   3000
Electronics  128000  42666.666667  18000  85000

In [23]:
# Merging Datasets
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4],
    "Customer_Name": ["Ali", "Sara", "Ahmed", "Ayesha"]
})
sales = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 1],
    "Sales": [50000, 30000, 45000, 20000]
})
merged_df = pd.merge(customers, sales, on="Customer_ID")

merged_df

   Customer_ID Customer_Name  Sales
0            1           Ali  50000
1            1           Ali  20000
2            2          Sara  30000
3            3         Ahmed  45000

In [24]:

# Concatenation

sales_part1 = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard"],
    "Sales": [85000, 1500, 3000]
})

sales_part2 = pd.DataFrame({
    "Product": ["Monitor", "Printer"],
    "Sales": [25000, 18000]
})
combined_sales = pd.concat(
    [sales_part1, sales_part2],
    ignore_index=True
)

combined_sales

    Product  Sales
0    Laptop  85000
1     Mouse   1500
2  Keyboard   3000
3   Monitor  25000
4   Printer  18000

In [25]:
import pandas as pd

df = pd.read_excel("Week_3_Day_2_Retail_Sales_Dataset.xlsx")

df

,Order_ID,Order_Date,Customer,Product,Category,Region,Quantity,Unit_Price,Sales
0,ORD001,2026-01-05,Ali Khan,Laptop,Electronics,Lahore,2,85000,170000
1,ORD002,2026-01-07,Sara Ahmed,Mouse,Accessories,Karachi,5,1500,7500
2,ORD003,2026-01-10,Ahmed Raza,Keyboard,Accessories,Islamabad,3,3000,9000
3,ORD004,2026-01-12,Ayesha Malik,Monitor,Electronics,Lahore,1,25000,25000
4,ORD005,2026-01-15,Hassan Ali,Printer,Office,Faisalabad,2,18000,36000
5,ORD006,2026-01-18,Fatima Noor,Laptop,Electronics,Karachi,1,85000,85000
6,ORD007,2026-01-21,Usman Tariq,Headphones,Accessories,Lahore,4,5000,20000
7,ORD008,2026-01-24,Maham Iqbal,Mouse,Accessories,Islamabad,6,1500,9000
8,ORD009,2026-01-27,Bilal Shah,Keyboard,Accessories,Multan,2,3000,6000
9,ORD010,2026-01-30,Hira Aslam,Monitor,Electronics,Karachi,1,25000,25000
10,ORD011,2026-02-02,Ali Khan,Printer,Office,Lahore,3,18000,54000
11,ORD012,2026-02-05,Sara Ahmed,Laptop,Electronics,Islamabad,1,85000,85000
12,ORD013,2026-02-08,Ahmed Raza,Headphones,Accessories,Faisalabad,2,5000,10000
13,ORD014,2026-02-11,Ayesha Malik,Mouse,Accessories,Lahore,5,1500,7500
14,ORD015,2026-02-14,Hassan Ali,Monitor,Electronics,Multan,2,25000,50000
15,ORD016,2026-02-17,Fatima Noor,Keyboard,Accessories,Karachi,4,3000,12000
16,ORD017,2026-02-20,Usman Tariq,Laptop,Electronics,Lahore,1,85000,85000
17,ORD018,2026-02-23,Maham Iqbal,Printer,Office,Islamabad,2,18000,36000
18,ORD019,2026-02-26,Bilal Shah,Headphones,Accessories,Karachi,3,5000,15000
19,ORD020,2026-02-28,Hira Aslam,Mouse,Accessories,Faisalabad,7,1500,10500

In [26]:
df.head()
df.shape
df.columns
df.info()
df.describe()
df[["Product", "Category", "Sales"]]
df[df["Sales"] > 20000]
df.sort_values("Sales", ascending=False)
df.groupby("Category")["Sales"].sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    20 non-null     object
 1   Order_Date  20 non-null     datetime64[ns]
 2   Customer    20 non-null     object
 3   Product     20 non-null     object
 4   Category    20 non-null     object
 5   Region      20 non-null     object
 6   Quantity    20 non-null     int64
 7   Unit_Price  20 non-null     int64
 8   Sales       20 non-null     int64
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 1.5+ KB

Category
Accessories    106500
Electronics    525000
Office         126000
Name: Sales, dtype: int64