In [ ]:
import pandas as pd

data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Ayesha", "Hassan"],
    "Age": [25, None, 30, 28, None],
    "City": ["Lahore", "Karachi", None, "Islamabad", "Lahore"],
    "Sales": [50000, 30000, None, 45000, 60000]
}

df = pd.DataFrame(data)

df

  Customer   Age       City    Sales
0      Ali  25.0     Lahore  50000.0
1     Sara   NaN    Karachi  30000.0
2    Ahmed  30.0       None      NaN
3   Ayesha  28.0  Islamabad  45000.0
4   Hassan   NaN     Lahore  60000.0

In [ ]:
df.isnull().sum()

Customer    0
Age         2
City        1
Sales       1
dtype: int64

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [ ]:
df["City"] = df["City"].fillna("Unknown")

In [ ]:
df

  Customer        Age       City    Sales
0      Ali  25.000000     Lahore  50000.0
1     Sara  27.666667    Karachi  30000.0
2    Ahmed  30.000000    Unknown      NaN
3   Ayesha  28.000000  Islamabad  45000.0
4   Hassan  27.666667     Lahore  60000.0

In [ ]:
data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Ayesha", "Hassan"],
    "Age": [25, None, 30, 28, None],
    "City": ["Lahore", "Karachi", None, "Islamabad", "Lahore"],
    "Sales": [50000, 30000, None, 45000, 60000]
}

df_drop = pd.DataFrame(data)

df_drop

  Customer   Age       City    Sales
0      Ali  25.0     Lahore  50000.0
1     Sara   NaN    Karachi  30000.0
2    Ahmed  30.0       None      NaN
3   Ayesha  28.0  Islamabad  45000.0
4   Hassan   NaN     Lahore  60000.0

In [ ]:
df_clean = df_drop.dropna()

df_clean

  Customer   Age       City    Sales
0      Ali  25.0     Lahore  50000.0
3   Ayesha  28.0  Islamabad  45000.0

In [ ]:
df_clean.shape

(2, 4)

In [ ]:
data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Sara"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Sales": [50000, 30000, 45000, 50000, 30000]
}

df_dup = pd.DataFrame(data)

df_dup

  Customer       City  Sales
0      Ali     Lahore  50000
1     Sara    Karachi  30000
2    Ahmed  Islamabad  45000
3      Ali     Lahore  50000
4     Sara    Karachi  30000

In [ ]:
df_dup.duplicated().sum()

np.int64(2)

In [ ]:
df_no_duplicates = df_dup.drop_duplicates()

df_no_duplicates

  Customer       City  Sales
0      Ali     Lahore  50000
1     Sara    Karachi  30000
2    Ahmed  Islamabad  45000

In [ ]:
data = {
    "Customer": ["Ali", "Sara", "Ahmed"],
    "Age": ["25", "30", "28"],
    "Sales": ["50000", "30000", "45000"]
}

df_types = pd.DataFrame(data)

df_types

  Customer Age  Sales
0      Ali  25  50000
1     Sara  30  30000
2    Ahmed  28  45000

In [ ]:
df_types["Age"] = df_types["Age"].astype(int)
df_types["Sales"] = df_types["Sales"].astype(float)

In [ ]:
df_types.dtypes

Customer     object
Age           int64
Sales       float64
dtype: object

In [ ]:
import pandas as pd

sales = pd.Series([10000, 12000, 15000, 11000, 13000, 14000, 90000])

Q1 = sales.quantile(0.25)
Q3 = sales.quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Q1: 11500.0
Q3: 14500.0
IQR: 3000.0
Lower Limit: 7000.0
Upper Limit: 19000.0

In [ ]:
outliers = sales[(sales < lower_limit) | (sales > upper_limit)]

print("Outliers:")
print(outliers)

Outliers:
6    90000
dtype: int64

In [ ]:
cities = pd.Series([
    "Lahore",
    "lahore",
    "LAHORE",
    " Lahore ",
    "karachi",
    "KARACHI"
])

print("Before:")
print(cities)

cities_clean = cities.str.strip().str.title()

print("\nAfter:")
print(cities_clean)

Before:
0      Lahore
1      lahore
2      LAHORE
3     Lahore
4     karachi
5     KARACHI
dtype: object

After:
0     Lahore
1     Lahore
2     Lahore
3     Lahore
4    Karachi
5    Karachi
dtype: object

In [ ]:
customers = pd.Series([
    "  Ali Khan  ",
    "sara ahmed",
    "AHMED RAZA",
    "  Ayesha Malik",
    "HASSAN ALI  "
])

print("Before:")
print(customers)

cleaned_customers = customers.str.strip().str.title()

print("\nAfter:")
print(cleaned_customers)

Before:
0        Ali Khan
1        sara ahmed
2        AHMED RAZA
3      Ayesha Malik
4      HASSAN ALI
dtype: object

After:
0        Ali Khan
1      Sara Ahmed
2      Ahmed Raza
3    Ayesha Malik
4      Hassan Ali
dtype: object

In [ ]:
dates = pd.Series([
    "2026-01-05",
    "2026-02-10",
    "2026-03-15"
])

print("Before:")
print(dates.dtypes)

dates = pd.to_datetime(dates)

print("\nAfter:")
print(dates.dtypes)

print("\nDates:")
print(dates)

Before:
object

After:
datetime64[ns]

Dates:
0   2026-01-05
1   2026-02-10
2   2026-03-15
dtype: datetime64[ns]

In [7]:
data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "City": ["Lahore", "Lhr", "Karachi", "Khi"]
}

df_replace = pd.DataFrame(data)

df_replace

  Customer     City
0      Ali   Lahore
1     Sara      Lhr
2    Ahmed  Karachi
3   Ayesha      Khi

In [8]:
df_replace["City"] = df_replace["City"].replace({
    "Lhr": "Lahore",
    "Khi": "Karachi"
})

df_replace

  Customer     City
0      Ali   Lahore
1     Sara   Lahore
2    Ahmed  Karachi
3   Ayesha  Karachi

In [9]:
data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Sales": [5000, 15000, 8000, 25000]
}

df_apply = pd.DataFrame(data)

df_apply

  Customer  Sales
0      Ali   5000
1     Sara  15000
2    Ahmed   8000
3   Ayesha  25000

In [10]:
def sales_level(sales):
    if sales >= 10000:
        return "High"
    else:
        return "Low"

In [11]:
df_apply["Sales_Level"] = df_apply["Sales"].apply(sales_level)

df_apply

  Customer  Sales Sales_Level
0      Ali   5000         Low
1     Sara  15000        High
2    Ahmed   8000         Low
3   Ayesha  25000        High

In [2]:

import pandas as pd

data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Age": [25, 30, -5, 28],
    "Sales": [5000, 15000, -2000, 25000]
}

df_validation = pd.DataFrame(data)

df_validation

  Customer  Age  Sales
0      Ali   25   5000
1     Sara   30  15000
2    Ahmed   -5  -2000
3   Ayesha   28  25000

In [3]:
df_validation[df_validation["Age"] < 0]

  Customer  Age  Sales
2    Ahmed   -5  -2000

In [4]:
df_validation[df_validation["Sales"] < 0]

  Customer  Age  Sales
2    Ahmed   -5  -2000

In [5]:
import pandas as pd

data = {
    "Customer": ["  Ali  ", "Sara", "Ali", "AHMED", "Ayesha"],
    "Age": ["25", "30", "25", None, "28"],
    "City": ["Lahore", "Karachi", "Lahore", " lahore ", None],
    "Sales": [5000, 15000, 5000, 8000, None]
}

df_messy = pd.DataFrame(data)

print("Original Data:")
display(df_messy)

# 1. Remove duplicate records
df_messy = df_messy.drop_duplicates()

# 2. Fix Age data type
df_messy["Age"] = pd.to_numeric(df_messy["Age"], errors="coerce")

# 3. Fill missing Age with the average
df_messy["Age"] = df_messy["Age"].fillna(df_messy["Age"].mean())

# 4. Fill missing City
df_messy["City"] = df_messy["City"].fillna("Unknown")

# 5. Clean text
df_messy["Customer"] = df_messy["Customer"].str.strip().str.title()
df_messy["City"] = df_messy["City"].str.strip().str.title()

# 6. Fill missing Sales
df_messy["Sales"] = df_messy["Sales"].fillna(df_messy["Sales"].mean())

print("\nCleaned Data:")
display(df_messy)

Original Data:

  Customer   Age      City    Sales
0    Ali      25    Lahore   5000.0
1     Sara    30   Karachi  15000.0
2      Ali    25    Lahore   5000.0
3    AHMED  None   lahore    8000.0
4   Ayesha    28      None      NaN

Cleaned Data:

  Customer   Age     City    Sales
0      Ali  25.0   Lahore   5000.0
1     Sara  30.0  Karachi  15000.0
2      Ali  25.0   Lahore   5000.0
3    Ahmed  27.0   Lahore   8000.0
4   Ayesha  28.0  Unknown   8250.0